apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: contrib-nginx-ingress
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contrib-nginx-ingress
    spec:
#      nodeSelector:
#        role: web
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-ingress-controller:0.8.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10249
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        # use downward API
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --nginx-configmap=$(POD_NAMESPACE)/contrib-nginx-ingress
        resources:
          limits:
            cpu: 500m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
