apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.0.2
    spec:
      nodeSelector:
        role: web
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster:v1.0.2
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
